repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: flake8-uv
        name: flake8 via uv
        entry: uv run flake8
        language: system
        types: [python]
