services:
  parser:
    image: ghcr.io/juuwel/recipe-parser:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_VERSION=2022-06-28
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"