name: Check Version Bump

on:
    pull_request:
        branches: [release]

jobs:
    check-version-bump-recipe-extractor:
        runs-on: ubuntu-latest
        steps:
            - name: Check out head branch code
              uses: actions/checkout@v5
              with:
                  path: head

            - name: Check out base branch code
              uses: actions/checkout@v5
              with:
                  ref: ${{ github.event.pull_request.base.ref }}
                  path: base

            - name: Check version bump
              shell: bash
              run: |
                  # Compare pyproject.toml
                  BASE_VERSION=$(grep -E '^\s*version\s*=' base/apps/extraction-service/pyproject.toml | head -1 | sed -E 's/^\s*version\s*=\s*\"([^\"]+)\"/\1/')
                  HEAD_VERSION=$(grep -E '^\s*version\s*=' head/apps/extraction-service/pyproject.toml | head -1 | sed -E 's/^\s*version\s*=\s*\"([^\"]+)\"/\1/')

                  echo "BASE_VERSION: $BASE_VERSION"
                  echo "HEAD_VERSION: $HEAD_VERSION"
                  diff base/apps/extraction-service/pyproject.toml head/apps/extraction-service/pyproject.toml || true

                  if [ "$BASE_VERSION" = "$HEAD_VERSION" ]; then
                      echo "pyproject.toml version has not been bumped!"
                      exit 1
                  fi

                  # Compare Chart.yaml version
                  BASE_CHART_VERSION=$(grep '^version:' base/deploy/recipe-extractor/Chart.yaml | head -1 | awk '{print $2}' | tr -d '"')
                  HEAD_CHART_VERSION=$(grep '^version:' head/deploy/recipe-extractor/Chart.yaml | head -1 | awk '{print $2}' | tr -d '"')
                  if [ "$BASE_CHART_VERSION" = "$HEAD_CHART_VERSION" ]; then
                      echo "Chart.yaml version has not been bumped!"
                      exit 1
                  fi

                  # Compare Chart.yaml appVersion
                  BASE_APP_VERSION=$(grep '^appVersion:' base/deploy/recipe-extractor/Chart.yaml | head -1 | awk '{print $2}' | tr -d '"')
                  HEAD_APP_VERSION=$(grep '^appVersion:' head/deploy/recipe-extractor/Chart.yaml | head -1 | awk '{print $2}' | tr -d '"')
                  if [ "$BASE_APP_VERSION" = "$HEAD_APP_VERSION" ]; then
                      echo "Chart.yaml appVersion has not been bumped!"
                      exit 1
                  fi

                  echo "Version bump detected in all required files."
